global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#igor_efimov'
