version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      backend-network:
        aliases:
          - mongo_db
          - post_db
  ui:
    build: ./ui
    image: ${USERNAME}/ui:1.0
    ports:
      - 9292:9292/tcp
    networks:
      frontend-network:
        aliases:
          - ui
  post:
    build: ./post-py
    image: ${USERNAME}/post:1.0
    networks:
      frontend-network:
        aliases:
          - post
      backend-network:
        aliases:
          - post
  comment:
    build: ./comment
    image: ${USERNAME}/comment:1.0
    networks:
      frontend-network:
        aliases:
          - comment
      backend-network:
        aliases:
          - comment

volumes:
  post_db:

networks:
  frontend-network:
    ipam:
      config:
        - subnet: 10.0.1.0/24
  backend-network:
    ipam:
      config:
        - subnet: 10.0.2.0/24